# Generated by Django 2.0 on 2018-03-05 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jualtiket', '0002_auto_20180306_0204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tanggal',
        ),
        migrations.AddField(
            model_name='tiket',
            name='tanggal',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='tanggal di tentukan'),
            preserve_default=False,
        ),
    ]
