# Generated by Django 2.0 on 2018-03-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jualtiket', '0003_auto_20180306_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiket',
            old_name='nama_tiket',
            new_name='nama_film',
        ),
        migrations.AlterField(
            model_name='tiket',
            name='tanggal',
            field=models.DateTimeField(verbose_name='tanggal'),
        ),
    ]
