# Generated by Django 2.0 on 2018-03-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jualtiket', '0004_auto_20180306_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='posisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deret_duduk', models.CharField(max_length=2)),
                ('tiket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jualtiket.Tiket')),
            ],
        ),
    ]
