# Generated by Django 2.0 on 2018-03-06 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jualtiket', '0006_hargasatuan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hargaSatuan',
        ),
        migrations.AddField(
            model_name='tiket',
            name='harga_satuan',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
