# Generated by Django 2.0 on 2018-03-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jualtiket', '0007_auto_20180306_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='deskripsi',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='posisi',
            name='deret_duduk',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='tiket',
            name='harga_satuan',
            field=models.CharField(max_length=7),
        ),
    ]
